# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise – MPN(82834525-2348-4472-9e60-1927eb73b2ba)'
    appType: 'webAppLinux'
    WebAppName: 'ewomakitchen'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'JAVA|11-java11'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: - task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN(4)(82834525-2348-4472-9e60-1927eb73b2ba)'
    appType: 'webAppLinux'
    appName: 'webappserver'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'JAVA|11-java11'package'
